### ISSUE TITLE
Infinite rendering loop if adding a TX with zero from & to

### ISSUE THREAD

**Issue by alehuo** [jehna/kryptovero.fi#13]
When adding a new transaction that has zero from & to values, the application goes into an infinite loop and crashes.

![image](https://user-images.githubusercontent.com/7612995/132804859-aa714701-359d-41df-bdc4-545137e5af55.png)

**Comment by jehna** [comment]
Nice catch! There should probably be a check for disallowing zero values. Trading from zero or to zero does not really make sense right 🤔

**Comment by jehna** [comment]
Did some fixing for the logic. Can you check if the issue is still reproduceable?

**Comment by alehuo** [comment]
Working fine now 👍
